apiVersion: v2
name: nlweb

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 2.11.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "2023.1.1"

home: https://www.neotys.com/neoload
description: A Helm chart for deploying NeoLoad Web on Kubernetes
icon: https://www.neotys.com/favicon-32x32.png
keywords:
  - Neotys
  - Tricentis
  - NeoLoad Web
  - NLWeb
  - NLW
  - nlweb
sources:
 - https://github.com/Neotys-Labs/helm-neoload-web
