### ReplicaSet configuration
replicaCount:
  frontend: 2
  backend: 2

### NLWeb configuration
neoload:
  configuration:
    # The secret key must be at least 8 characters long
    secretKey: YOUR_CUSTOM_SECRET_KEY
    backend:
      mongo:
        host: YOUR_MONGODB_HOST_URL
        port: 27017
      # Enable licensing features (VUHs) by setting this token, or leave it empty
      licensingPlatformToken:
securityContext:
  runAsUser: 2000

### MongoDB user configuration
mongodb:
  usePassword: true
  mongodbUsername: YOUR_MONGODB_USER
  mongodbPassword: YOUR_MONGODB_PASSWORD

### Services host configuration
services:
  webapp:
    host: neoload-web.mycompany.com
  api:
    host: neoload-web-api.mycompany.com
  files:
    host: neoload-web-files.mycompany.com

domain: .mycompany.com

### Ingress configuration
### Choose your preferred ingress controller configuration
ingress:
  ## If the cluster has multiple ingress controllers set the ingressClassName to the proper value, default value is "nginx"
  ##
  # spec:
  #   ingressClassName: 
  enabled: true
  # Replace these annotations accordingly if you are not using the nginx ingress controller
  annotations:
    # nginx
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_ignore_client_abort "on";  
    nginx.ingress.kubernetes.io/proxy-body-size: 0
    # Enable sticky sessions for HA
    # More parameters here : https://kubernetes.github.io/ingress-nginx/examples/affinity/cookie/
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/session-cookie-max-age: 3600
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: true

  ### TLS configuration
  ### Uncomment if you want to secure your app with https
#  tls:
#    - secretName: tls-secret
#      secretCertificate: |-
#        -----BEGIN CERTIFICATE-----
#        YOUR_CERTIFICATE
#        -----END CERTIFICATE-----
#      secretKey: |-
#        -----BEGIN PRIVATE KEY-----
#        YOUR_PRIVATE_KEY
#        -----END PRIVATE KEY-----
