{{- if .Values.ingress.enabled -}}
{{- $namespace := .Release.Namespace -}}
{{- $labels := include "nlweb.labels" . -}}
{{- $fullName := include "nlweb.fullname" . -}}
{{- range $index, $tls := .Values.ingress.tls }}

{{- if and $tls.secretCertificate $tls.secretKey -}}

{{- $secretNameKey := printf "ingress.tls[%d].%s" $index "secretName" -}}
{{- $certMapKey := printf "ingress.tls[%d].%s" $index "secretCertificate" -}}
{{- $keyMapKey := printf "ingress.tls[%d].%s" $index "secretKey" -}}

{{- $secretName := $tls.secretName -}}

{{- $nameRequiredMessage := printf "You need to specify a unique secret name. (--set %s=my-tls-secret)" $secretName $certMapKey -}}
{{- $certRequiredMessage := printf "You need to specify an existing certificate for your '%s' secret. (--set %s=YOUR_CERTIFICATE)" $secretName $certMapKey -}}
{{- $keyRequiredMessage := printf "You need to specify an existing key for your '%s' secret. (--set %s=YOUR_KEY)" $secretName $keyMapKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $fullName $secretName | required $nameRequiredMessage }}
  namespace: {{ $namespace }}  
  labels:
    {{- $labels | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $tls.secretCertificate | required $certRequiredMessage | b64enc }}
  tls.key: {{ $tls.secretKey | required $keyRequiredMessage | b64enc }}

---

{{- end -}}
{{- end -}}
{{- end -}}