apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nlweb.secrets.key.name" . }}
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "nlweb.labels" . | nindent 4 }}
type: Opaque
{{- $previous := lookup "v1" "Secret" .Release.Namespace (include "nlweb.secrets.key.name" .) }}
data:
  nlwSecretKey: {{ .Values.neoload.configuration.secretKey | required "You need to specify a NLW secret key. (--set neoload.configuration.secretKey=mySecretKey)" | toString | b64enc | quote }}
  {{- if and ($previous) ($previous.data) ($previous.data.internalTokenSecret) }}
  internalTokenSecret: {{ $previous.data.internalTokenSecret }}
  {{- else }}
  internalTokenSecret: {{ randAlphaNum 128 | nospace | b64enc | quote }}
  {{- end }}
