apiVersion: v1
kind: Service
metadata:
  name: {{ include "nlweb.fullname" . }}-svc-hazelcast
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nlweb.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  {{- if eq (include "nlweb.ha.mode" .) "DNS" }}
  clusterIP: None
  {{- end }}
  ports:
    - port: 5701
      protocol: "TCP"
      name: http
  selector:
    {{ include "nlweb.selectorLabels" . | nindent 4 }}